# Generated by Django 3.1.6 on 2021-02-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цель')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.SlugField(allow_unicode=True, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.SlugField(allow_unicode=True, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetask')),
            ],
            bases=('tasks.basetask',),
        ),
        migrations.AddField(
            model_name='basetask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tasks.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='basetask',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tasks.Tag', verbose_name='Метки'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetask')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='tasks.task', verbose_name='История')),
            ],
            options={
                'ordering': ['-updated'],
            },
            bases=('tasks.basetask',),
        ),
    ]
