# Generated by Django 3.1.6 on 2021-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-deadline']},
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее изменение'),
        ),
    ]
